##### General
# FPS to run in
fps: 60

# Print debug messages?
debug: false

##### Sound
# General sound volume. 0.0 -> 1.0
sound_volume: 0.25

# Background music volume. 0.0 -> 1.0
background_volume: 0.025
background_music: false

##### UI
# Fonts to use
font_name: Courier
small_font_name: Courier

# Text colors
text_color: 0xffeeeeee
small_text_color: 0xffcccccc

# XY positions of UI elements.
positions:
  background:
  - 0
  - 0
  caption:
  - 693
  - 582
  card_status:
  - 5
  - 579
  order_title:
  - 95
  - 445
  order_clubs:
  - 105
  - 470
  order_diamonds:
  - 105
  - 490
  order_spades:
  - 105
  - 510
  order_hearts:
  - 105
  - 530
  bad_card:
  - 228
  - 420
  game_over:
  - 215
  - 290
  you_won:
  - 260
  - 270
  quit_or_restart:
  - 155
  - 310
